modeltest2/urls.py
"""
Definition of urls for modeltest2.
"""

from datetime import datetime
from django.urls import path, re_path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views
import django.contrib.auth.forms
from app.views import EventList


urlpatterns = [
    #common shiz
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    
    # group management
    path("group/create/", views.creategroup, name="creategroup"),
    path("group/join/", views.joingroup, name="joingroup"),
    
    # event management
    path('event/all/', views.events, name='events'),
    path("event/add/", views.CreateEventView.as_view(), name="addevent"),
    path('event/modify/<str:pk>/', views.eventsettings, name='eventsettings'),
    path('event/remove/<str:pk>/', views.eventremove, name='eventremove'),
    path('event/cancel/<str:pk>/', views.cancelevent, name='cancelevent'),
    path('event/join/<str:pk>/', views.joinevent, name='joinevent'),
    
    # user management
    path("register/", views.register, name="register"),
    path('user/', EventList.as_view(), name="user"),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Kirjaudu',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
]

app/models.py
"""
Definition of models.
"""

from django.db import models
from django.contrib.auth.models import User, Group, Permission, AbstractUser
import datetime
from django.utils import timezone


class Person(AbstractUser):
    bio = models.TextField(max_length = 500, blank = True, default = None, null = True)
    events = models.ManyToManyField('Event', through = 'EventsJoined', blank = True, default = None)

    class Meta:
        permissions = [('can_eat_pizzas', 'Can eat pizzas')]

    def __str__(self):
        self.username
        if len(self.first_name) == 0:
            return f'{self.username}'
        else:
            return f'{self.first_name} {self.last_name}'


class EventTypes(models.Model):
    name = models.CharField(max_length = 128)
    badgecolor = models.CharField(max_length = 20, default = "bg-success")

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length = 128)
    creator = models.ForeignKey(Person, null = True, on_delete = models.SET_NULL, default = None, related_name = 'creator')
    members = models.ManyToManyField(Person, through = 'EventsJoined', blank = True, default = None)
    type = models.ForeignKey(EventTypes, on_delete = models.CASCADE)
    max = models.SmallIntegerField()
    date = models.DateTimeField()
    description = models.TextField(max_length = 500, default = '')
    group = models.ForeignKey(Group, null = True, on_delete = models.SET_NULL, default = None, related_name = 'group')

    class Meta:
        ordering = ['date']

    def __str__(self):
        return f'{self.date} {self.type.name} {self.name}'


class EventsJoined(models.Model):
    person = models.ForeignKey(Person, on_delete = models.CASCADE)
    event = models.ForeignKey(Event, on_delete = models.CASCADE)
    date = models.DateField(default = timezone.now)
    join = models.BooleanField(default = False)

    class Meta:
        unique_together = [['person', 'event']]

    def cancelevent(self):
        self.join = False
        self.date_cancel = datetime.date.today()

    def jointoevent(self):
        self.join = True
        self.date_joined = datetime.date.today()

    def __str__(self):
        return f'{self.event.name} {self.person.username}'

class News(models.Model):
    creator = models.ForeignKey(Person, null = True, on_delete = models.SET_NULL, default = None, related_name = 'newscreator')
    date = models.DateField(default = timezone.now)
    description = models.TextField(max_length = 500, default = '')
    
    

app/templates/app/about - Copy.html
{% extends "app/layout.html" %}
{% block content %}
<div class="container">
<h2>{{ title }}</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

<div class="shadow-lg ">Larger s
<h2>Asterisk Glyph</h2>
      <p>Asterisk icon: <span class="glyphicon glyphicon-asterisk"></span></p>    
      <p>Asterisk icon as a link:
        <a href="#">
          <span class="glyphicon glyphicon-asterisk"></span>
        </a>
      </p>
      <p>Asterisk icon on a button:
        <button type="button" class="btn btn-default btn-sm">
          <span class="glyphicon glyphicon-asterisk"></span> Asterisk
        </button>
      </p>
      <p>Asterisk icon on a styled link button:
        <a href="#" class="btn btn-info btn-lg">
          <span class="glyphicon glyphicon-asterisk"></span> Asterisk
        </a>
      </p> 
    asdf
   <span class="border">asd
    fas
    df
    asdf
    asd</span> 
    fa
    sdf</br>
    asdf
    hadow</div>

    
    
</div>

{% endblock %}

app/templates/app/addevent.html
{% extends "app/layout.html" %}

{% block content %}
<div class="container">
<h2>{{ title }}</h2>
<h3>{{ message }}</h3>
{% if user.is_authenticated == True %}

    <form method="POST" class="form-group">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Luo tapahtuma</button>
    </form>
    </div>
{% else %}
    <div class="alert alert-info" role="alert">
  Tapahtumiin luominen vaatii kirjautumisen.
</div>
{% endif %}

{% endblock %}

app/templates/app/creategroup.html
{% extends "app/layout.html" %}

{% block content %}
<div class="container">
<h2>{{ title }}</h2>
<h3>{{ message }}</h3>
{% if user.is_authenticated == True %}
    <form method="POST" class="form-group">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Luo porukka</button>
    </form>
    </div>
{% else %}
    <div class="alert alert-info" role="alert">
  Tapahtumiin luominen vaatii kirjautumisen.
</div>
{% endif %}

{% endblock %}

app/templates/app/event_form.html
{% extends "app/layout.html" %}

{% block content %}
<div class="container">
<h2>{{ title }}</h2>
<h3>{{ message }}</h3>
{% if user.is_authenticated == True %}

    <form method="POST" class="form-group">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Luo tapahtuma</button>
    </form>
    </div>
{% else %}
    <div class="alert alert-info" role="alert">
  Tapahtumiin luominen vaatii kirjautumisen.
</div>
{% endif %}

{% endblock %}

app/templates/app/event_list.html
{% extends "app/layout.html" %}
{% load suodattimet %}

{% block deletemodal %}
  <div class="modal fade" id="CopyClipboardEventModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><i class="bi bi-clipboard-check">Koodi kopioitu!</i></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
    		<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div> 
{% endblock %}

{% block content %}

        <div class="container">
        <h2>{{ title }}</h2>
        <h3>{{ message }}</h3>

        <h1>{{ request.user }}</h1>
        <hr />

    <h2>Tapahtumat, joissa mukana</h2>
            {% regroup object_list|dictsort:"group.name" by group as event_list %}

        <ul>
            {% for group in event_list %}
            <li>
                {{ group.grouper }}
                <ul>
                    {% for event in group.list %}
                    <li>{{ event.name }}: {{ event.date }}</li>
                    {% endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>
    
    
            <h5>Porukat joissa mukana</h5>
        <div class="row">
        {% for group in request.user.groups.all %}
      
      	<div class="col-md-4">
	        <div class="card">
			<svg class="card-img-top" xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" class="bi bi-people" viewBox="0 0 16 16">
			  <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z"/>
			</svg>
	            <div class="card-body">
	                <h4 class="card-title">{{ group }}</h4>
	                <form>
	                    <div class="form-group row">
	                    
	                    <div class="alert alert-primary" role="alert">
	                        <i class="bi bi-tag"> Kutsukoodi</i>
							<input id="koodi{{ group.id }}" type="text" readonly class="form-control-plaintext" value="{{ group.name|md5 }}">
								
								<a data-bs-toggle="modal" data-bs-target="#CopyClipboardEventModal" data-bs-whatever="@mdo" onclick="myFunction(koodi{{ group.id }})" class="btn btn-success" href="#" role="button"><i class="bi bi-clipboard-check"> Kopioi</i></a>

						</div>

	    
	                    </div>
	                </form>
	                <h5>Tyypit</h5>
	                <ul class="list-group list-group-flush">
	                    {% for user in group.user_set.all %}
	                    <li class="list-group-item"><i class="bi bi-person"> {{ user }} </i></li>
	                    {% endfor %}
	                </ul>
	
	                <ul>
	                    {% for event in group.events_set.all %}
	                    <li>{{ event }}</li>
	                    {% endfor %}
	                </ul>
	            </div>
	        </div>
        </div>
        {% endfor %}
            	
    	<h3>Muutoshistoria</h3>

     <ul class="list-group">
    {% for change in changes %}
    
    

    	{% if change.action_flag == 3 %}
    	<li  class="list-group-item list-group-item-danger">
    	 {% elif change.action_flag == 2 %}
    	<li  class="list-group-item list-group-item-warning">
    	    	 {% elif change.action_flag == 1 %}
    	<li  class="list-group-item list-group-item-success">
    	{% endif %}
    	
    	{{ change.change_message }}
    	
    	</li>
    {% endfor %}
    </ul>
        </div>
{% endblock %}

app/templates/app/events.html
{% extends "app/layout.html" %}
{% load suodattimet %}
{% block content %}

<div class="container">
<h2>{{ title }}</h2>
<!-- <h3>{{ message }}</h3> -->

{% if user.is_authenticated %}

        {% regroup events|dictsort:"group.name" by group as event_list %}
            {% for group in event_list %}
                <h3>{{ group.grouper }}</h3>
               
                <div class="row">
                {% for event in group.list %}

                 <div class="col-md-4">
                <div class="card card-body">
                    <a name="{{ event.id }}"></a>
                    <h2>{{ event.name }}</h2>
                    
                    <div>
                        <span class="badge {{ event.type.badgecolor }}">{{ event.type }}</span></br><i class="bi bi-calendar2-event"> {{ event.date }}</i></div>
                        <hr>
                    <div>                        
                        <p class="font-monospace">
                        {{ event.description|linebreaksbr }}
                        </p>
                    </div>
                    <hr>
                    <div>
                        {% for join in event.eventsjoined_set.all %}
                            {% if join.join == True %}
                                <span class="badge bg-light text-dark">{{ join.person }}</span>
                            {% endif %}
                        {% endfor %}
                    </div>
                    {% if user.is_authenticated == True %}
                        <div class="btn-group" role="group" aria-label="Osalasdfsdlistu">
                                <!-- Evil bitlevel hacking, link is set to hidden, if user is joined to the event. Notice the "<a" -->
                            {% if event.eventsjoined_set.all|length < event.max %}
                                <a {% for join in event.eventsjoined_set.all %}
                                    {% if join.person == request.user and join.join == True %}
                                        hidden 
                                    {% endif %}
                                {% endfor %} id="{{ event.id }}_joinbtn" class="btn btn-success" href="{% url 'joinevent' event.id  %}" type="button" ><i class="bi bi-hand-thumbs-up"> Oon tulos!</i> <span class="badge bg-secondary"><em>{{ event.members.all|length }}/{{ event.max }}</em></span></a>
                            {% endif %}
                            {% for join in event.eventsjoined_set.all %}
                                {% if join.person == request.user and join.join == True %}
                                    <a class="btn btn-warning" href="{% url 'cancelevent' event.id  %}" type="button"><i class="bi bi-hand-thumbs-down"></i> En tuukkaan!<span class="badge bg-secondary"><em> {{ event.members.all|length }}/{{ event.max }}</em></span></a>
                                {% endif %}
                            {% endfor %}

                            {% if event.creator == request.user %}
                                    <a class="btn btn-dark" href="{% url 'eventsettings' event.id  %}" type="button"><i class="bi bi-gear-fill"></i></a>

                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
                    {% endfor %}
            
          </div>
       <hr />
            {% endfor %}
         
    {% else %}
<div class="alert alert-info" role="alert">
  Tapahtumiin ilmoittautuminen vaatii kirjautumisen.
</div>
{% endif %}
        <!--/row-->
 </div>
{% endblock %}

app/templates/app/eventsettings.html
{% extends "app/layout.html" %}

{% block deletemodal %}
  <div class="modal fade" id="deleteEventModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><i class="bi bi-trash">Poista tapahtuma?</i></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
            <a data-bs-toggle="modal" data-bs-target="#deleteEventModal" data-bs-whatever="@mdo" class="btn btn-danger" href="{% url 'eventremove' id %}" type="button"><i class="bi bi-trash"></i></a>
    		<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Peruuta</button>
      </div>
    </div>
  </div>
</div> 
{% endblock %}


{% block content %}
<div class="container">
<h2>{{ title }}</h2>
<h3>{{ message }}</h3>
{% if user.is_authenticated == True %}
    <form method="POST" class="form-group">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Muokkaa</button>
        <!-- <a data-bs-toggle="modal" data-bs-target="#deleteEventModal" data-bs-whatever="@mdo" class="btn btn-danger" href="#" type="button"><i class="bi bi-trash"></i></a>-->
        <a class="btn btn-danger" href="{% url 'eventremove' id %}" type="button"><i class="bi bi-trash">Poista (poistaa heti)</i></a>
    </form>
    
    <ul>
    {% for change in changes %}
    	<li>{{ change.change_message }}</lie>
    {% endfor %}
    </ul>
    </div>
{% else %}
    <div class="alert alert-info" role="alert">
  Tapahtumiin luominen vaatii kirjautumisen.
</div>
{% endif %}

{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Oletko tulossa vai et?</h1>
          <p>T&auml;m&auml; i&auml;nikuinen ongelma, joka on riesana kaikissa seuroissa, kaveriporukoissa, taloyhti&ouml;iss&auml; ja jopa kippokutsuilla.</p>
          <p>OOKKO tarjoaa ratkaisun.</p>
          <p><a class="btn btn-primary btn-lg" href="{% url 'register' %}" role="button">Liity nyt! &raquo;</a></p>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns 
        <div class="row">
          <div class="col-md-4">
            <h2>Liity!</h2>
            <p>Liity nyt!</p>
            <p><a class="btn btn-secondary" href="{% url 'register' %}" role="button">Liity &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Luo!</h2>
            <p>Luo tapahtumia.</p>
            <p><a class="btn btn-secondary" href="{% url 'addevent' %}" role="button">Luo &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Osallistu!</h2>
            <p>Osallistu muiden tapahtumiin.</p>
            <p><a class="btn btn-secondary" href="{% url 'events' %}" role="button">Osallistu &raquo;</a></p>
          </div>
        </div>
        <hr>-->
          <div class="row">
                    <div class="col-md-4">
                    <div class="card text-white bg-success overflow-hidden">
                        <div class="card-body bg-success">
                            <div class="rotate">
                                
                            </div>
                            <h6 class="text-uppercase">K&auml;ytt&auml;ji&auml;</h6>
                            <h1 class="display-1"><i class="bi bi-person"></i> {{ users.all|length }}</h1>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card text-white bg-danger overflow-hidden">
                        <div class="card-body bg-danger">
                            <div class="rotate">
                                <i class="fa fa-list fa-4x"></i>
                            </div>
                            <h6 class="text-uppercase">Tapahtumia</h6>
                            <h1 class="display-1"><i class="bi bi-calendar2-event"></i> {{ events_joinable.all|length }} / {{ events.all|length }}</h1>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card text-white card-info overflow-hidden">
                        <div class="card-body bg-info">
                            <div class="rotate">
                                <i class="fa fa-twitter fa-5x"></i>
                            </div>
                            <h6 class="text-uppercase">Osallistumisia</h6>
                            <h1 class="display-1"><i class="bi bi-hand-thumbs-up"></i> {{ joins|length }}</h1>
                        </div>
                    </div>
                </div>
            </div>
    

      </div> <!-- /container -->
<br />

  <div class="container">



	    <div class="my-3 p-3 bg-body rounded shadow-sm">
	    <h6 class="border-bottom pb-2 mb-0">Uutiset</h6>
	    {% for nw in news %}
		    <div class="d-flex text-muted pt-3">
		      <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
		
		      <p class="pb-3 mb-0 small lh-sm border-bottom">
		        <strong class="d-block text-gray-dark">{{ nw.creator }} / {{ nw.date }}</strong>
		       	{{ nw.description }}
		      </p>
		    </div>
    	{% endfor %}
    <!--<small class="d-block text-end mt-3">
      <a href="#">All updates</a>
    </small>-->
  </div>

     <!-- <h3>Tulevat omat tapahtumat</h3>
      <div class="list-group">
            <span class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">Palvelu uudelleennimetty!</h5>
              <small>HOT!</small>
            </div>
            <p class="mb-1">Palvelu asettui viimein oman nimens&Auml; taakse ja se on OOKKOTULOS!</p>
            <small>Juha</small>
          </span>
          <span class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">Porukoiden luominen ja kutsulinkit</h5>
              <small>HOT!</small>
            </div>
            <p class="mb-1">Nyt on mahdollista luoda porukoita eri tarpeisiin ja jokaiselle porukalle tapahtumia. Kutsukoodi voidaan antaa uusille tyypeille. Jokaisen porukan omat tapahtumat ovat vain n&auml;kyviss&auml;.<br />
              Kutsulinkit ovat asetusvalikossa. <a href="{% url 'user' %}" >Asetukset</a></p>
            <small>Juha</small>
          </span>
    </div>-->
      </div>
{% endblock %}

app/templates/app/joingroup.html
{% extends "app/layout.html" %}

{% block content %}
<div class="container">
<h2>{{ title }}</h2>
<h3>{{ message }}</h3>
{% if user.is_authenticated == True %}
    <form method="POST" class="form-group">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Liity porukkaan</button>
    </form>
    </div>
{% else %}
    <div class="alert alert-info" role="alert">
  Tapahtumiin luominen vaatii kirjautumisen.
</div>
{% endif %}

{% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}
<div class="container">
<h2>{{ title }}</h2>
    <div class="row">
        <div class="col-md-4">

            <section id="loginForm">
                <form action="." method="post" class="form-horizontal">
                    {% csrf_token %}
                    <h4>Kirjaudu sis&auml;&auml;n</h4>
                    <hr />
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="inputGroup-sizing-lg"><i class="bi bi-file-person"></i></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <div class="col-md-10">
                            {{ form.username }}
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="inputGroup-sizing-lg"><i class="bi bi-lock-fill"></i></span>
                        <div class="col-md-10">
                            {{ form.password }}
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="hidden" name="next" value="/" />
                            <button class="w-100 btn btn-lg btn-primary" type="submit" value="Log in" class="btn btn-primary">Kirjaudu</button>
                        </div>
                    </div>

                </form>
            </section>
        </div>
        <div class="col-md-4">
            <section id="socialLoginForm"></section>
        </div>
    </div>
</div>


{% endblock %}


{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
{% load static %}
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="form-inline my-2 my-lg-0">
    {% csrf_token %}

        <a class="btn btn-warning" href="{% url 'user' %}" role="button"><i class="bi bi-gear-fill"></i></a>
        <a class="btn btn-danger my-2 my-sm-0" href="javascript:document.getElementById('logoutForm').submit()" role="button"><i class="bi bi-person-circle" width="32" height="32" style=" color: inherit;"> {{ user.username }}</i></a>

       

</form>

{% else %}
        <form class="form-inline my-2 my-lg-0">
          <a class="btn btn-success my-2 my-sm-0" href="{% url 'login' %}" role="button"><i class="bi bi-person-circle" width="32" height="32" style="color: inherit;"></i></a>
        </form>

{% endif %}

app/templates/app/register.html
{% extends "app/layout.html" %}

{% block content %}

<div class="container">
<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>


	{% if form.errors %}
	<div class="alert alert-danger" role="alert">
  	{{ form.errors }}
	</div>
	{% endif %}

<form method="POST" class="form-group">
    {% csrf_token %}
    {{ form }}



    <button type="submit" class="btn btn-success">Liity</button>

</form>
</div>
{% endblock %}